### PR TITLE
Useful modifications

### PR DESCRIPTION
**Pull request by Nixon-Joseph**
Added default ItemTemplate to CardView so you don't need to define one for simple displays.

Added call to FirePositionChanged when manually updating the index.

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph thanks) I will validate it today-tomorrow)
Then we discuss changes.
Thanks!

**Comment by Nixon-Joseph** [comment]
Sounds good. 

I could think of only one improvement:

Instead of always calling FirePositionChanged - I should have created a new property like (bool)FirePositionChangedWhenIndexChanged (defaults to false) and only fire the event when that is true, that way it doesn't change existing behavior.

**Comment by AndreiMisiukevich** [comment]
So, as for firing event.
I think it will be more right, if we
1) Make CurrentIndexProperty default value -1 instead of 0
2) modify SetCurrentView method like below
```csharp
        protected virtual void SetCurrentView(bool canResetContext = false)
        {
            if(TryAutoNavigate())
            {
                return;
            }

            if (TryResetContext(canResetContext, _currentView, CurrentContext))
            {
                return;
            }

			if (Items != null || CurrentContext != null)
			{
				_currentView = GetView(CurrentIndex, PanItemPosition.Current, FrontViewProcessor);
				if (_currentView == null && CurrentIndex >= 0)
				{
					ShouldIgnoreSetCurrentView = true;
					CurrentIndex = -1;
				}
				else if (CurrentIndex != OldIndex)
				{
					var isNextSelected = CurrentIndex > OldIndex;
					FirePositionChanging(isNextSelected);
					FirePositionChanged(isNextSelected);
				}
			}

            SetupBackViews();
        }
```
3) Add FirePositionChanging on AutoNavigatingStarted
4) Add FirePositionChanged on AutoNavigatingEnded

What do you think? From my point of view it would be more elegant.

**Comment by AndreiMisiukevich** [comment]
As for second:
Maybe it would be better to check for null ItemTemplate in PrepareView method?
smth like this

```csharp
            var context = GetContext(index, panIntemPosition);
            if (context == null)
            {
                return null;
            }

            var template = ItemTemplate;
            if(template == null)
            {
                return context as View;
            }
..........
```

What is your opinion?

If you agree with me, could you implement this positions?

**Comment by AndreiMisiukevich** [comment]
"Added default ItemTemplate to CardView so you don't need to define one for simple displays." and another side of your implementation.. in your case users will be able to use only ContentView as root view.. I think it's something specific. If user want to use AbsoluteLayout or StackLayout or others, he still will have to implement itemTemplate

**Comment by AndreiMisiukevich** [comment]
Do you agree with me by each point?

**Comment by Nixon-Joseph** [comment]
Yes, I believe your implementation of the default item template is better. Anything they pass in will just work unless it needs more bindings, which would need a custom item template anyway. 

As for the event firing I'll look into it more when I get to work. I'm on my phone now, and can't really follow the code on this screen. But it looks good from what I can tell.

**Comment by AndreiMisiukevich** [comment]
@Nixon-Joseph thanks, colleague!

as for first point I've just added part of code below
```
                                else if (CurrentIndex != OldIndex)
				{
					var isNextSelected = CurrentIndex > OldIndex;
					FirePositionChanging(isNextSelected);
					FirePositionChanged(isNextSelected);
				}
```

in case of your agreeing with me after checking code by you.. could you pls refactor your code? I will merge it

**Comment by Nixon-Joseph** [comment]
Updated the code as suggested. I fully agree on all points, I think that's a much better use.

I did wonder though, should the calls in the AutoNavigation methods always pass in `true`, because it's auto navigating? Or should it use the `CurrentIndex > OldIndex` logic? I did the latter because it's technically more accurate.

**Comment by Nixon-Joseph** [comment]
Perhaps I don't understand IsAutoNavigating. Just set it to true, and nothing seems to be different. Do I need to do more?

**Comment by AndreiMisiukevich** [comment]
Nice, but i noticed one more thing.
I mean determining of direction of aniamation (FirePositionChanging and FirePositionChanged)
but i will do it myself)
Thanks!

**Comment by Nixon-Joseph** [comment]
Oh, alright. I didn't see any way to set a direction or start the auto process or anything. I'll look into it more and see if I can figure it out. I'm still pretty shallow into the project, and so don't have a full understanding yet.
Thanks!.

**Comment by AndreiMisiukevich** [comment]
I will create new version with our changes

**Comment by Nixon-Joseph** [comment]
Awesome thanks!

**Comment by AndreiMisiukevich** [comment]
https://www.nuget.org/packages/CardsView/1.3.9

**Pull request merged**
