### PR TITLE
Feature/Coverflow

### PR DESCRIPTION
**Pull request by Phenek**
There it is ;)

### CODE REVIEW

**Comment by Phenek** [comment]
It's not free of bug but Ok for now.
There is some comments inside.

**Comment by AndreiMisiukevich** [comment]
Great!
I will check it later

**Comment by AndreiMisiukevich** [comment]
@Phenek I've checked it quickly
Looks nice. Good job.

Just a question: is it possible to set cards in center (default position)?

Because now, i see full size of 1st and 2nd cards and small part of 3rd
Can we show the same parts of 1s and 3rd and full size of 2nd?
Hope it's clear

**Comment by Phenek** [comment]
There is two property:
ViewPosition : this one is positioning the view on Left, center, or right side
 (default is Center right now)
FirstItemPosition: is setting the first Item on the leftmost, 
the most centered, or the most right view (default Left for now)

The right position is to support in next enhancement RTL disposition.

So what do you expect is to set both property at the center by default?
And you case is about a circular list? the expectation could depend of this too.

Let me know

**Comment by AndreiMisiukevich** [comment]
@Phenek really, don't know)
I think, I should merge it
Refactor a little, then we can test it

I will do it today-tomorrow

**Comment by Phenek** [comment]
Great because I will need a second point of view,
to perform a good recycler view logic during the end animation.

This will allow us to add a Velocity Scroll Property, (the things I need :)))

**Comment by Phenek** [comment]
Maybe the property ViewPosition could be called ViewAlignment

**Comment by AndreiMisiukevich** [comment]
@Phenek agreed

**Pull request merged**
