### PR TITLE
few small fixes

### PR DESCRIPTION
**Pull request by JTOne123**
I did those changes during reviewing controls
1) the formatting - sorry for that, I had to do it :)
2) the description - first what I looking for in readme was XAML example and it is the reason
3) droid manifest - what sense to set up target version for the example? it confused me for few minutes before I had built an app in my SDK version
4) UWP version - no custom renderer - min target

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
@JTOne123 thanks for your contributing) Could you pls check my comment and resolve this issue?)

**Comment by JTOne123** [comment]
Hi there, thank you!
This is the nice project and you're doing a great work!

Replace spaces with tabs in all projects. [Frankly, I prefer default VS settings but it is your project and your rules :) ]

**Comment by AndreiMisiukevich** [comment]
@JTOne123  thanks for you time)

**Comment by AndreiMisiukevich** [comment]
@JTOne123 btw, I will be grateful, if you set "star" on this repo) it gives me more motivation for work )

**Comment by JTOne123** [comment]
Готово ;) странно что не поставил, а эти звездочки чему рейтинг дают?

**Comment by AndreiMisiukevich** [comment]
@JTOne123 ну проекту, моему профилю) ну в целом видно, что этим кто-то пользуется и есть смысл что-то улучшать/делать)

**Pull request merged**
