### PR TITLE
Window resizing crash

### PR DESCRIPTION
**Pull request by JTOne123**
1. Fixed crash if the adding method in UI thread throw the exception
2. The removing should be at invoked at UI thread in case of InvalidOperationException as well

### CODE REVIEW

**Comment by AndreiMisiukevich** [comment]
@JTOne123 Hi

Could you add something like that method

```cshapr
 private void ExecutePreventInvalidOperationException(Action action)
        {
            try
            {
                action?.Invoke();
            }
            catch (InvalidOperationException)
            {
                Device.BeginInvokeOnMainThread(() => {
                    try
                    {
                        action?.Invoke();
                    }
                    catch(InvalidOperationException ex)
                    {
                        System.Diagnostics.Debug.WriteLine("Couldn't handle InvalidOperationException");
                    }
                });
            }
        }
```

and call it by that way

```csharp
ExecutePreventInvalidOperationException(() => Children.Insert(0, view));
```

instead of duplicating code

**Comment by JTOne123** [comment]
done!

**Comment by AndreiMisiukevich** [comment]
Thanks
Could you please apply it to all the same places?
for example https://github.com/JTOne123/CardView/blob/master/PanCardView/CardsView.cs#L1348

**Comment by JTOne123** [comment]
done, I guess only the insert the same place

**Pull request merged**
